version: '3'
services:
  spark-master:
    image: ozlevka/spark-master-debian:2.2.0
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: ozlevka/spark-worker-debian:2.2.0
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8081"
  spark-worker-2:
    image: ozlevka/spark-worker-debian:2.2.0
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8082"
  
  development:
    build:
      context: .
    ports: 
      - 7777:7777
      - 7776:7776
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    volumes:
      - "./:/home/vscode/dev"
    depends_on: 
      - spark-master
      - spark-worker-1
      - spark-worker-2
